pipeline {
    agent any

    tools {
        jdk 'Java17'
        maven 'Maven'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Pulling from GitHub'
                git branch: 'main',
                    credentialsId: 'mygithubcred',
                    url: 'https://github.com/karthikthiramdas/wipjen.git'
            }
        }

        stage('Test Code') {
            steps {
                echo 'JUNIT Test case execution started'
                dir('indiaproj') {
                    sh 'mvn clean test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: '**/target/surefire-reports/*.xml'
                    echo 'Test Run Completed'
                }
            }
        }

        stage('Build Project') {
            steps {
                echo 'Building Java project'
                dir('indiaproj') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image'
                dir('indiaproj') {
                    sh 'docker build -t myjavaproj:1.0 .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker tag myjavaproj:1.0 karthikthiramdas/myjavaproj:1.0
                    docker push karthikthiramdas/myjavaproj:1.0
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('indiaproj') {
                    sh '''
                    echo "Deploying to Kubernetes..."
                    kubectl apply -f deployment.yaml
                    kubectl apply -f services.yaml

                    echo "=============================="
                    echo "KUBERNETES APPLICATION URL:"
                    minikube service indiaproj-service --url
                    echo "=============================="
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'PIPELINE SUCCESSFUL!'
        }
        failure {
            echo 'PIPELINE FAILED!'
        }
    }
}
