pipeline {
    agent any

    tools {
        jdk 'Java17'
        maven 'Maven'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Pulling from Github'
                git branch: 'main',
                    credentialsId: 'mygithubcred',
                    url: 'https://github.com/karthikthiramdas/wipjen.git'
            }
        }

        stage('Test Code') {
            steps {
                echo 'JUNIT Test case execution started'
                dir('indiaproj') {
                    sh 'mvn clean test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: '**/target/surefire-reports/*.xml'
                    echo 'Test Run Completed'
                }
            }
        }

        stage('Build Project') {
            steps {
                echo 'Building Java project'
                dir('indiaproj') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build the Docker Image') {
            steps {
                echo 'Building Docker Image'
                dir('indiaproj') {
                    sh 'docker build -t myjavaproj:1.0 .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                echo 'Running Java Application'
                sh '''
                docker rm -f myjavaproj-container || true
                docker run -d --name myjavaproj-container myjavaproj:1.0
                '''
            }
        }
    }

    post {
        success {
            echo 'BUILD AND RUN SUCCESSFUL!'
        }
        failure {
            echo 'OOPS!!! Failure.'
        }
    }
}
